# 站点的名称
site_name: super for mkdocs
# 站点的地址
site_url: 'http://127.0.0.1:8000/mkdocs-super/'
# 主题配置项
theme:
  name: null
  custom_dir: super
  locale: zh_CN

# 文档目录树
nav:
- 首页: index.md
- 环境部署-单机版: 
  - 系统要求: setup/system-requirements.md
  - 服务端:
    - windows部署: setup/rhapsody_windows.md
    - centos7部署: setup/rhapsody_centos7.md
    - 容器部署: setup/docker_installer.md
  - 监控程序:
    - Dashboard部署: setup/rhapsody-dashboard.md
  # - docker安装: setup/docker_setup_centos7.md
- 通讯点:
  - Web Service Client操作: comm/Web_Service_Client.md
  - Web Service Host操作: comm/Web_Service_Host.md
- 过滤器:
  - database: filter/database.md
  - JavaScript: filter/JavaScript.md
  - freemarker: filter/freemarker.md
- 其它:
  # - 命名规范: other/naming_conventions.md
  - 平台证书安装:
    - 根证书安装: other/cacert-install-root.md
    - 中间机构证书安装: other/cacert-install-agent.md
  - SSL证书到期处理:
    - SSL证书到期后处理方案: other/https-ssl.md
  - api: 
    - 常用api: other/api.md
  - 正则表达式: filter/regexp.md
  - 常见问题: other/FAQ.md